### ISSUE TITLE
cannot copy the lib to esp32 cam on windows 

### ISSUE THREAD

**Issue by ani-rudh** [SpotlightKid/mrequests#1]
Hi,

I have followed the instructions to copy the files to ESP32 flash (using the install shell script), it seems to fail
![image](https://user-images.githubusercontent.com/15331399/133433330-5f424933-e9d7-4f78-9f9e-95a25e14f284.png)

Is there a way to install this library in an alternative way?
Dev environment: VS code with pymakr on windows

My use case is to send (POST) a picture from esp32 cam board to telegram bot via api call.

Thank you for any help :)

**Comment by SpotlightKid** [comment]
The mrequests modules can be copied to your micropython board like any other code. Use you favourite tool to copy `mrequests.py` to your board's flash filesystem root directory, or `mrequests.mpy`, if you compiled it with `mpy-cross`. The other modules are only needed for additional functionality like form-encoding or URL parsing and they can be copied in the normal way as well.

The install script happens to use `rshell`, but you can use any other supported way to get code to your board as well.
