### ISSUE TITLE
Micropython freezing on ssl.wrap_socket

### ISSUE THREAD

**Issue by MATTYGILO** [SpotlightKid/mrequests#11]
Hi I really appreciate this GitHub repo and it has incredibly useful so far.

I am currently have a problem where my MicroPython is freezing on code `ssl.wrap_socket`. I have found this issue on the micropython forum [https://forum.micropython.org/viewtopic.php?t=4356](https://forum.micropython.org/viewtopic.php?t=4356). However, I'm uncertain about what I can do to fix it.

**Comment by SpotlightKid** [comment]
Sorry, this is the wrong place to handle this issue. Please discuss this on the forum or in the micropython issue tracker.
