### ISSUE TITLE
"Warning: Comparison between bytes and str"

### ISSUE THREAD

**Issue by skoeb** [SpotlightKid/mrequests#3]
Hi there, 
this seems like a great project which fixes many of my hair-pulling annoyances with urequests. I implemented this in my code, and it's working great, but I'm now getting a lot of additional logging for "Warning: Comparison between bytes and str" that I wasn't getting before with urequests.

I'm getting bursts of three on `mrequests.get()` with a url in string format, and a dictionary of string headers. 

Is there an easy fix here? 

Thanks for your work on this!

**Comment by SpotlightKid** [comment]
> Is there an easy fix here?

The easy fix is not passing `str`, but always `bytes` for all data, which goes over the wire, i.e. the URL, the headers (names and values) and request body.

**Comment by SpotlightKid** [comment]
Further investigation has lead me to the conclusion that this warning is unavoidable when using MicroPython and a dictionary containing keys, which are `str` instances, is passed in via the  `headers` keyword argument to `mrequests.request` (or its wrappers like `get`, `post` etc.).

So, to avoid it, always use `bytes` instances for keys and values of the headers dictionary.
