### ISSUE TITLE
NoneType Error on self.read()

### ISSUE THREAD

**Issue by macalencar** [SpotlightKid/mrequests#6]
When I get a response without "Content-Length" specified on header the lib shows this:

File "./src/mrequests.py", line 161, in read
TypeError: unsupported types for __lt__: 'int', 'NoneType'

I had to change the line 232 from 
self._cached = self.read(size=None) 
to
self._cached = self.read() 

Now it works!

https://github.com/SpotlightKid/mrequests/blob/4ba5cc62c5609360c18eb147605680ca66f4dfea/mrequests.py#L232

**Comment by SpotlightKid** [comment]
You don't seem to be using the latest version of the code. Please re-test with the current version in the repo.

**Comment by SpotlightKid** [comment]
Closing this due to no further feedback.

Feel free to re-open *if* you can provide additional information.
