### ISSUE TITLE
[FR] `Response.readinto` is desired.

### ISSUE THREAD

**Issue by jacklinquan** [SpotlightKid/mrequests#8]
It would be nicer if `Response` class had a `readinto` method.
When reading from chunked responses, a memory constrained device may want to reuse a `bytearray` instead of allocating a new `bytearray` or `bytes` object every time.

**Comment by SpotlightKid** [comment]
Yes, that would be good.

However, I probably currently won't have the time to implement *and test* that.

PRs very welcome!
